jobs:
  - job: LintCode
    displayName: Lint Code
    steps:
      - script: az bicep build --file $(Build.SourcesDirectory)/main.bicep
        name: LintBicepCodeMain
        displayName: Run Bicep Linter for Resource Group
    